<?php
return [
        CORE_DIR . 'Request.class.php',
        CORE_DIR . 'Router.class.php',
        CORE_DIR . 'FactoryProxy.class.php',
        CORE_DIR . 'Factory.class.php',
        CORE_DIR . 'Context.class.php',
        CORE_DIR . 'RequestContext.class.php',
        CORE_DIR . 'ResponseContext.class.php',
        CORE_DIR . 'Dispatcher.class.php',
        CORE_DIR . 'SmvcObject.class.php',
        CORE_DIR . 'exception/SessionException.class.php',
        CORE_DIR . 'Session.class.php',
        CORE_DIR . 'controller/BaseController.class.php',
        CORE_DIR . 'dao/BaseDBDAO.class.php',
        CORE_DIR . 'dao/BaseRedisDBDAO.class.php',
        CORE_DIR . 'dao/UserSplitDBDAO.class.php',
        CORE_DIR . 'service/BaseService.class.php',
        CORE_DIR . 'view/View.class.php',
        CORE_DIR . 'SmvcConf.class.php',
        CORE_DIR . 'functions.php',
        CORE_DIR . 'exception/ExceptionHandler.class.php',
        VENDOR_DIR . '/Medoo/Medoo.php',
];